#:schema node_modules/wrangler/config-schema.json
name = "cloudfare-telegram-template"
main = "src/index.ts"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat_v2"]

[observability]
enabled = true

[vars]
# Do not commit real values to version control.
TELEGRAM_BOT_TOKEN = "7863912376:AAG2xznH6UEh8UkGtaPTX6tcjubu058WSHY"
TELEGRAM_CHAT_ID = "-1002261132272"
HELIUS_API_KEY = "586b18e8-9087-46d0-a5d9-200bbede5435"
AUTH_TOKEN = "UW0JcEFFZ/mSA84tza+0Kqz52CT4qzW/NlGrfHuT0qo="